"""add is_active in conversation table

Revision ID: eefc36dc0216
Revises: 20261003_01
Create Date: 2026-10-04 11:06:49.748754

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'eefc36dc0216'
down_revision: str | Sequence[str] | None = '20261003_01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_active')
    # ### end Alembic commands ###
